project:
  type: website

website:
  title: "Entropy"
  favicon: "images/favicon/entropy_ai.png"
  navbar:
    logo: "images/favicon/entropy_ai.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/FarshadTabasi
      - icon: mastodon
        href: https://mastodon.social/@farshadtabasinejad@fosstodon.org
format:
  html:
    css: styles.css
    eval: true
    theme:
      light: [Yeti, theme.scss]



